services:
  web:
    image: nginx
    volumes:
    - $HOME/public_html:/usr/share/nginx/html
    ports:
    - "18000:80"
    restart: always

  # host metrics monitoring is better provided by node exported + prometheus
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100

  # long time values are better supported by influxdb 
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - $PWD/influx_docker_dir/data:/var/lib/influxdb2
      - $PWD/influx_docker_dir/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION="10y"
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    volumes:
      - ./grafana_docker_dir/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_docker_dir/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    restart: always

networks:
  default:
